config/routes.rb
Rails.application.routes.draw do
  resources :trapezes
  resources :triangles
  resources :squares
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/square.rb
class Square < ApplicationRecord
    validate :side_valid

    def perimeter
        sides * side
    end

    def sides
        4
    end

    def area
        side ** 2
    end

    private

    def side_valid
        if side
            errors.add(:side, "must be greather than 0") if side <= 0
            errors.add(:side, "must be less than or equal to 1000") if side > 1000
        else
            errors.add(:side, "must be present")
        end
    end
end

app/models/trapeze.rb
class Trapeze < ApplicationRecord
    validate :side_valid
    validate :bigger_side_valid
    validate :smaller_side_valid

    def area
        ((biggerBase + smallerBase) * side)/2
    end

    def perimeter
        side + smallerBase + biggerBase + Integer.sqrt(side**2 + (biggerBase - smallerBase)**2)
    end

    private 
    def side_valid
        if side
            errors.add(:side, 'Lado precisa ser maior que 0') if side <= 0
            errors.add(:side, 'Lado precisa ser menos que 50') if side >= 50
        else
            errors.add(:side, 'Lado precisa existir')
        end
    end

    def bigger_side_valid
        if biggerBase
            errors.add(:biggerBase, 'O lado maior precisa ser maior que 0') if biggerBase <= 0
        else
            errors.add(:biggerBase, 'O lado maior precisa existir')
        end
    end

    def smaller_side_valid
        if smallerBase
            errors.add(:smallerBase, 'O lado menor precisa ser meior que 0') if smallerBase <= 0
        else
            errors.add(:smallerBase, 'O lado menor precisa existir')
        end
    end
end

app/models/triangle.rb
class Triangle < ApplicationRecord
    validate :side_valid

    def perimeter
        sides * side
    end

    def sides
        3
    end

    def area
        (side ** 2 * Math.sqrt(3)) / 4
    end

    private

    def side_valid        
        errors.add(:side, "must be greather than 0") if side <= 0
        errors.add(:side, "must be less than or equal to 1000") if side > 1000
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/squares_controller.rb
class SquaresController < ApplicationController
  before_action :set_square, only: [:show, :edit, :update, :destroy]

  # GET /squares
  # GET /squares.json
  def index
    @squares = Square.all
  end

  # GET /squares/1
  # GET /squares/1.json
  def show
  end

  # GET /squares/new
  def new
    @square = Square.new
  end

  # GET /squares/1/edit
  def edit
  end

  # POST /squares
  # POST /squares.json
  def create
    @square = Square.new(square_params)

    respond_to do |format|
      if @square.save
        format.html { redirect_to @square, notice: 'Square was successfully created.' }
        format.json { render :show, status: :created, location: @square }
      else
        format.html { render :new }
        format.json { render json: @square.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /squares/1
  # PATCH/PUT /squares/1.json
  def update
    respond_to do |format|
      if @square.update(square_params)
        format.html { redirect_to @square, notice: 'Square was successfully updated.' }
        format.json { render :show, status: :ok, location: @square }
      else
        format.html { render :edit }
        format.json { render json: @square.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squares/1
  # DELETE /squares/1.json
  def destroy
    @square.destroy
    respond_to do |format|
      format.html { redirect_to squares_url, notice: 'Square was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_square
      @square = Square.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def square_params
      params.require(:square).permit(:side)
    end
end

app/controllers/trapezes_controller.rb
class TrapezesController < ApplicationController
  before_action :set_trapeze, only: [:show, :edit, :update, :destroy]

  # GET /trapezes
  # GET /trapezes.json
  def index
    @trapezes = Trapeze.all
  end

  # GET /trapezes/1
  # GET /trapezes/1.json
  def show
  end

  # GET /trapezes/new
  def new
    @trapeze = Trapeze.new
  end

  # GET /trapezes/1/edit
  def edit
  end

  # POST /trapezes
  # POST /trapezes.json
  def create
    @trapeze = Trapeze.new(trapeze_params)

    respond_to do |format|
      if @trapeze.save
        format.html { redirect_to @trapeze, notice: 'Trapeze was successfully created.' }
        format.json { render :show, status: :created, location: @trapeze }
      else
        format.html { render :new }
        format.json { render json: @trapeze.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trapezes/1
  # PATCH/PUT /trapezes/1.json
  def update
    respond_to do |format|
      if @trapeze.update(trapeze_params)
        format.html { redirect_to @trapeze, notice: 'Trapeze was successfully updated.' }
        format.json { render :show, status: :ok, location: @trapeze }
      else
        format.html { render :edit }
        format.json { render json: @trapeze.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trapezes/1
  # DELETE /trapezes/1.json
  def destroy
    @trapeze.destroy
    respond_to do |format|
      format.html { redirect_to trapezes_url, notice: 'Trapeze was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trapeze
      @trapeze = Trapeze.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trapeze_params
      params.require(:trapeze).permit(:side, :biggerBase, :smallerBase)
    end
end

app/controllers/triangles_controller.rb
class TrianglesController < ApplicationController
  before_action :set_triangle, only: [:show, :edit, :update, :destroy]

  # GET /triangles
  # GET /triangles.json
  def index
    @triangles = Triangle.all
  end

  # GET /triangles/1
  # GET /triangles/1.json
  def show
  end

  # GET /triangles/new
  def new
    @triangle = Triangle.new
  end

  # GET /triangles/1/edit
  def edit
  end

  # POST /triangles
  # POST /triangles.json
  def create
    @triangle = Triangle.new(triangle_params)

    respond_to do |format|
      if @triangle.save
        format.html { redirect_to @triangle, notice: 'Triangle was successfully created.' }
        format.json { render :show, status: :created, location: @triangle }
      else
        format.html { render :new }
        format.json { render json: @triangle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /triangles/1
  # PATCH/PUT /triangles/1.json
  def update
    respond_to do |format|
      if @triangle.update(triangle_params)
        format.html { redirect_to @triangle, notice: 'Triangle was successfully updated.' }
        format.json { render :show, status: :ok, location: @triangle }
      else
        format.html { render :edit }
        format.json { render json: @triangle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /triangles/1
  # DELETE /triangles/1.json
  def destroy
    @triangle.destroy
    respond_to do |format|
      format.html { redirect_to triangles_url, notice: 'Triangle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_triangle
      @triangle = Triangle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def triangle_params
      params.require(:triangle).permit(:side)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/squares_helper.rb
module SquaresHelper
    def area_with_units(square)
        return "#{square.area} m2"
    end
end

app/helpers/trapezes_helper.rb
module TrapezesHelper
end

app/helpers/triangles_helper.rb
module TrianglesHelper
    def perimeter_with_units(triangle)
        return "#{triangle.perimeter} m"
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fgm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/squares/_form.html.erb
<%= form_with(model: square, local: true) do |form| %>
  <% if square.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(square.errors.count, "error") %> prohibited this square from being saved:</h2>

      <ul>
      <% square.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :side %>
    <%= form.text_field :side %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/squares/edit.html.erb
<h1>Editing Square</h1>

<%= render 'form', square: @square %>

<%= link_to 'Show', @square %> |
<%= link_to 'Back', squares_path %>

app/views/squares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Squares</h1>

<table>
  <thead>
    <tr>
      <th>Side</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @squares.each do |square| %>
      <tr>
        <td><%= square.side %></td>
        <td><%= area_with_units(square) %></td>
        <td><%= link_to 'Show', square %></td>
        <td><%= link_to 'Edit', edit_square_path(square) %></td>
        <td><%= link_to 'Destroy', square, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Square', new_square_path %>

app/views/squares/new.html.erb
<h1>New Square</h1>

<%= render 'form', square: @square %>

<%= link_to 'Back', squares_path %>

app/views/squares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Side:</strong>
  <%= @square.side %>
</p>

<%= link_to 'Edit', edit_square_path(@square) %> |
<%= link_to 'Back', squares_path %>

app/views/trapezes/_form.html.erb
<%= form_with(model: trapeze, local: true) do |form| %>
  <% if trapeze.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trapeze.errors.count, "error") %> prohibited this trapeze from being saved:</h2>

      <ul>
      <% trapeze.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :side %>
    <%= form.number_field :side %>
  </div>

  <div class="field">
    <%= form.label :biggerBase %>
    <%= form.number_field :biggerBase %>
  </div>

  <div class="field">
    <%= form.label :smallerBase %>
    <%= form.number_field :smallerBase %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trapezes/edit.html.erb
<h1>Editing Trapeze</h1>

<%= render 'form', trapeze: @trapeze %>

<%= link_to 'Show', @trapeze %> |
<%= link_to 'Back', trapezes_path %>

app/views/trapezes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trapezes</h1>

<table>
  <thead>
    <tr>
      <th>Side</th>
      <th>Biggerbase</th>
      <th>Smallerbase</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trapezes.each do |trapeze| %>
      <tr>
        <td><%= trapeze.side %></td>
        <td><%= trapeze.biggerBase %></td>
        <td><%= trapeze.smallerBase %></td>
        <td><%= link_to 'Show', trapeze %></td>
        <td><%= link_to 'Edit', edit_trapeze_path(trapeze) %></td>
        <td><%= link_to 'Destroy', trapeze, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trapeze', new_trapeze_path %>

app/views/trapezes/new.html.erb
<h1>New Trapeze</h1>

<%= render 'form', trapeze: @trapeze %>

<%= link_to 'Back', trapezes_path %>

app/views/trapezes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Side:</strong>
  <%= @trapeze.side %>
</p>

<p>
  <strong>Biggerbase:</strong>
  <%= @trapeze.biggerBase %>
</p>

<p>
  <strong>Smallerbase:</strong>
  <%= @trapeze.smallerBase %>
</p>

<%= link_to 'Edit', edit_trapeze_path(@trapeze) %> |
<%= link_to 'Back', trapezes_path %>

app/views/triangles/_form.html.erb
<%= form_with(model: triangle, local: true) do |form| %>
  <% if triangle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(triangle.errors.count, "error") %> prohibited this triangle from being saved:</h2>

      <ul>
      <% triangle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :side %>
    <%= form.text_field :side %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/triangles/edit.html.erb
<h1>Editing Triangle</h1>

<%= render 'form', triangle: @triangle %>

<%= link_to 'Show', @triangle %> |
<%= link_to 'Back', triangles_path %>

app/views/triangles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Triangles</h1>

<table>
  <thead>
    <tr>
      <th>Side</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @triangles.each do |triangle| %>
      <tr>
        <td><%= triangle.side %></td>
        <td><%= link_to 'Show', triangle %></td>
        <td><%= link_to 'Edit', edit_triangle_path(triangle) %></td>
        <td><%= link_to 'Destroy', triangle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Triangle', new_triangle_path %>

app/views/triangles/new.html.erb
<h1>New Triangle</h1>

<%= render 'form', triangle: @triangle %>

<%= link_to 'Back', triangles_path %>

app/views/triangles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Side:</strong>
  <%= @triangle.side %>
</p>

<%= link_to 'Edit', edit_triangle_path(@triangle) %> |
<%= link_to 'Back', triangles_path %>